version: "0.1"
services:
  db:
    image: "pgvector/pgvector:pg16"
    container_name: "db"
    ports:
      - "5432:5432"
    environment:
      "POSTGRES_DB": "POSTGRES_DB"
      "POSTGRES_USER": "${POSTGRES_USER}"
      "POSTGRES_PASSWORD": "${POSTGRES_PASSWORD}"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    restart: "unless-stopped"
    healthcheck:
      test:
        - "CMD-SHELL"
        - "pg_isready -U ${POSTGRES_USER} -d ragtag"
      interval: "10s"
      timeout: "5s"
      retries: 5
  api:
    image: "golang:1.19"
    container_name: "api"
    ports:
      - "8080:8080"
    environment:
      "DB_HOST": "db"
      "DB_PORT": "5432"
    depends_on:
      - "db"
